# Generated by Django 5.2.1 on 2025-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_images/default_pi.png', upload_to='profile_images'),
        ),
    ]
